# Instalar el sistema operativo y las dependencias necesarias
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND=dialog
ENV PUB_HOSTED_URL=https://pub.flutter-io.cn
ENV FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

# Descargar el SDK de Flutter desde el repositorio de Flutter en GitHub
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter

# Establecer la ruta del entorno de Flutter
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Ejecutar el doctor de Flutter
RUN flutter doctor

# Habilitar el soporte para Flutter web
RUN flutter channel master
RUN flutter upgrade
RUN flutter config --enable-web

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el contenido del proyecto
COPY . /app

# Construir la aplicación web de Flutter
RUN flutter build web

# Exponer el puerto 9000
EXPOSE 9000

# CMD para ejecutar el servidor directamente
CMD cd /app/build/web/ && python3 -m http.server 9000

