FROM docker.io/tensorflow/tensorflow:2.15.0.post1-gpu

WORKDIR /tf

COPY requirements.txt ./
RUN pip install --no-cache-dir --ignore-installed -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["flask", "--app", "server", "run", "--host", "0.0.0.0"]

